import React, { Component } from 'react'
import {Row, Col} from 'react-bootstrap';
export const PrivacyPolicy = () => {
    return (
        <div>
            <Row>
                <Col sm={12}>
                <div data-testid="richTextElement">
                        <h2>Privacy Policy</h2>
                        <p>Shopfree Technologies Private Limited, a company incorporated under the Companies Act, 2013 having registered office at No. 6, 1st Cross, Virupakshapura, Bangalore - 560097 (&ldquo;Shopfree&rdquo;, &ldquo;Company&rdquo; or &ldquo;we&rdquo; or &ldquo;us&rdquo; or &ldquo;our&rdquo;), provides automated text content through its website (referred to as &ldquo;Services&rdquo;) available at&nbsp;<a href="http://www.ellipsis-ai.com/" target="_blank" rel="noopener">www.ellipsis-ai.com</a>&nbsp;(referred to as &ldquo;Platform&rdquo;). Any service availed by users of the Platform, inclusive of the Creators (as defined in the Terms of Service), Customers (as defined in the Terms of Service) and the Visitors who visit the page (hereinafter referred to as&ldquo;you&rdquo;, &ldquo;your&rdquo; or &ldquo;User&rdquo;) through the Platform is conditioned upon your acceptance of the terms and conditions contained in Terms of Service as available on Platform and this privacy policy (&ldquo;Privacy Policy&rdquo;).</p>
                        <p>THIS PRIVACY POLICY HAS BEEN DRAFTED AND PUBLISHED IN ACCORDANCE WITH THE INFORMATION TECHNOLOGY ACT 2000; THE INFORMATION TECHNOLOGY (AMENDMENT) ACT 2008; AND THE INFORMATION TECHNOLOGY (REASONABLE SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OR INFORMATION) RULES 2011. THIS PRIVACY POLICY CONSTITUTES A LEGAL AGREEMENT BETWEEN YOU, AS A USER OF THE PLATFORM AND US, AS THE OWNER OF THE PLATFORM. YOU MUST BE A NATURAL PERSON WHO IS AT LEAST 18 YEARS OF AGE.</p>
                        <p>1. Introduction and applicability of the Privacy Policy</p>
                        <p>We are strongly committed to respecting your online privacy and recognize the need for appropriate protection and management of any personal information collected and/or collated by us.</p>
                        <p>The purpose of this Privacy Policy is to ensure that there is an intact charter to collect, use and protect any personal and/or sensitive data collected by us. This Policy defines our procedure for collection, usage, processing, disclosure and protection of any information obtained by us through the Platform.</p>
                        <p>Any reference made to Privacy Policy in this document shall mean and refer to the latest version of the Privacy Policy</p>
                        <p>2. Disclaimer</p>
                        <p>Please be advised that any Information (as defined herein below) procured by us, shall be:</p>
                        <p>processed fairly and lawfully for rendering the Services (as defined in Terms of Service);</p>
                        <p>obtained only for specified and lawful purposes, and not be used in any manner which is against the law or policy in force in India (&ldquo;Applicable Law&rdquo;); adequate, relevant and not excessive in relation to the purpose for which it is required; able to be reviewed by the User, from time to time and updated-if need arises; and not kept longer than for the time which it is required or the purpose for which it is required or as required by the applicable law.</p>
                        <p>WE SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGE SUSTAINED BY REASON OF ANY DISCLOSURE (INADVERTENT OR OTHERWISE) OF ANY DATA, IF THE SAME IS EITHER (A) REQUIRED FOR SHARING YOUR INFORMATION FOR LEGITIMATE PURPOSES; OR (B) WAS AFFECTED THROUGH NO FAULT, ACT, OR OMISSION OF THE COMPANY.</p>
                        <p>BY USING THE SERVICES, YOU EXPLICITLY ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, THE COLLECTION, USE AND TRANSFER OF THE DATA IN THE MANNER DESCRIBED HEREIN.</p>
                        <p>PLEASE READ THIS PRIVACY POLICY CAREFULLY AS IT AFFECTS YOUR RIGHTS AND LIABILITIES UNDER LAW.</p>
                        <p>3. Your consent</p>
                        <p>Please note that by providing the Information (as enumerated upon herein below), you provide your consent and authorize us to collect, use or disclose such Information for the business and research purposes and as stated in this Privacy Policy, the Terms of Service and as permitted or required by applicable law. Moreover, you understand and hereby consent that this Information may be transferred to any third party user for the purpose of providing Services through the Platform or to any third-party providers for rendering Services (as defined in the Terms of Service), any jointly developed or marketed services, payment processing, order fulfillment, customer services, data analysis, information technology services and such other services which enable us to provide Services through the Platform.</p>
                        <p>This Privacy Policy shall be enforceable against you in the same manner as any other written agreement. By visiting or accessing the Platform and voluntarily providing us with Information (including Personal Data), you are consenting to our use of the Information, in accordance with this Privacy Policy. If you do not agree with this Privacy Policy, you may refuse or withdraw your consent any time, or alternatively choose to not provide us with any Personal Information. Under such circumstances, your access to the Services we provide may be limited or we may be unable to render Services.</p>
                        <p>Such an intimation to withdraw your consent can be sent to&nbsp;<a href="mailto:support@ellipsis-ai.com" target="_self">support@ellipsis-ai.com</a></p>
                        <p>4. Types of information collected by us:</p>
                        <p>&ldquo;Personal Data&rdquo; means and includes any Information that relates to a natural person through which an individual is identified, such as the name, contact details, email address, gender, age, organisation name, organisation email id or any other relevant material provided by a User, including but not limited to information gathered through availing Services.</p>
                        <p>&ldquo;Technical Information&rdquo; means and includes any Information gathered through various technologies that may employ cookies, web beacons, or similar technologies to automatically record certain information from your device through which you use the Platform. This technical information may include your Internet Protocol (IP) address, device or browser type, Internet service provider (ISP), referring or exit pages, clickstream data, operating system, hardware model, operating system version, unique device identifiers, and mobile network. This data includes usage information and user statistics.</p>
                        <p>&ldquo;Locational Information&rdquo; shall mean and include the information obtained through GPS or other means, such as the geographical location of the User.</p>
                        <p>&ldquo;Information through use of our service&rdquo; means and includes information which is shared with us to avail our Services.</p>
                        <p>&ldquo;Non-Personal Information&rdquo; means and includes any information that does not reveal your specific identity, such as, browser information, information collected through Cookies (as defined below), pixel tags and other technologies, demographic information, etc. As is true with most websites, our Company gathers some information automatically when you visit the Platform. When you use the Platform, we may collect certain information about your computer or mobile to facilitate, evaluate and verify your use of the Platform. For example, we may store environmental variables, such as browser type, operating system, speed of the central processing unit (CPU), referring or exit web pages, click patterns and the internet protocol (IP) address of your computer. This information is generally collected in aggregate form, without identifying any user individually.</p>
                        <p>In addition to the above we may also collect the following data:</p>
                        <p>Account Details: These include your username and password and preferred account settings such as the language and time zone etc.</p>
                        <p>Billing Details: shall mean and include billing details such as name, address, email id and other financial information that corresponds to your mode of payment including but not limited to, credit card/ debit card details, net banking information, bank details etc. Please note that confidential information such as the CVV/ PIN Number and the net banking credentials will not be stored by us.</p>
                        <p>(The Personal Data, Technical Information, Locational Information, Non-Personal Information and additional information collected from the Creator and the Customer respectively are collectively referred to as &ldquo;Information&rdquo;).</p>
                        <p>5. Purpose of Collection and Usage of this Information</p>
                        <p>Depending on whether you are a Customer or Visitor, the data collected by us shall be used for availing our Services and utilised for other functions including but not limited to:</p>
                        <p>to render Services (as defined in the Terms of Service);&nbsp;</p>
                        <p>maintaining the Platform;</p>
                        <p>to evaluate the quality and competence of our personnel;</p>
                        <p>to resolve any complaints, you may have and ensure that you receive the highest quality of Services;</p>
                        <p>notifying you about changes to our Platform;</p>
                        <p>allowing you to participate in interactive features of our Platform when You choose to do so;</p>
                        <p>providing analysis or valuable information so that we can improve the Platform;</p>
                        <p>monitoring the usage of the Platform;</p>
                        <p>detecting, preventing and addressing technical issues;</p>
                        <p>analyse usage patterns and user preferences</p>
                        <p>improve user experience</p>
                        <p>notify you about new products and features</p>
                        <p>Business or Research Purposes: The Information saved and except Personal Information, is used for business or research purposes, including improving and customizing the Platform for ease of use and the products and services offered by us. We may archive this information to use it for future communications for providing updates and/or surveys.&nbsp;</p>
                        <p>Aggregating Information / Anonymized data: We may aggregate Information and analyse it in a manner to further accentuate the level of services that we offer to our customers. This Information includes average number of Users of the Platform, the average clicks of the services/, the features used, the response rate, etc. and other such statistics regarding groups or individuals. In doing so, we shall not be making disclosures of any Personal Information as defined above. </p>
                        <p>(Collectively referred to as &ldquo;Legitimate Purpose&rdquo;)</p>
                        <p>6. Disclosure and Sharing of Information</p>
                        <p>We do not rent, sell or disclose or share any Information that we collect from you, with third parties, save and except in order to provide you with the Services or for the Legitimate Purposes as specified above. Any such disclosure, if made, shall be in accordance with this Privacy Policy and as per the procedure prescribed by law and in compliance with our legal obligations. We may share your Information in circumstances and for the purposes as specified hereunder:</p>
                        <p>We shall share the information to the third-party service providers/ vendors, to provide you with the Services and to effectuate any activities that fall under the Legitimate Purpose for which such Information has been collected.</p>
                        <p>When compelled by law: We may disclose any Information provided by you on the Platform as may be deemed to be necessary or appropriate:</p>
                        <p>under applicable law, including laws outside your country of residence;</p>
                        <p>to comply with legal process;</p>
                        <p>to respond to requests from public and government authorities including public and government authorities including public and government authorities outside your country of residence;</p>
                        <p>to protect our operations or those of any of our affiliates;</p>
                        <p>to protect our rights, privacy, safety or property, and/that of our affiliates, you or others;</p>
                        <p>to allow us to pursue available remedies or limit the damages that we may sustain; or</p>
                        <p>to protect against legal liability;</p>
                        <p>to protect the personal safety of Users of the Platform;</p>
                        <p>to prevent or investigate possible wrongdoing in connection with the Platform.</p>
                        <p>Merger or Acquisition: We may share Information upon merger or acquisition of Company with another company. We shall transmit and transfer the Information upon acquisition or merger of Company with another company;</p>
                        <p>With our service providers: We may share Information with other service providers on a need to know basis, subject to obligations of confidentiality for provision of Services. We hereby clarify that Company works with institutions, vendors, partners, advertisers, and other service providers, including (but not limited) to those who provide products or services such as contact Information verification, website hosting, data analysis, providing infrastructure, information technology services, auditing services and other similar services, in different industries and categories of business by virtue of lawful contracts instituted between such third parties and Company to improve our product and services. Accordingly, we may share your Information with such service provider in order to provide you with Services;</p>
                        <p>Employees/Agents of Company: We follow a strict confidentiality policy with regard to disclosure of confidential information to our employees or other personnel. There may be situations, where we may disclose the confidential information only to those of our employees and other personnel on a need to know basis. Any breach of confidential information by the employees, personnel within the Company is dealt with stringently by us.</p>
                        <p>Except for the Information disclosed pursuant to sub-clause (a), (b), (c), (d) and (e) of Clause 6 above, Company may share Information, if you authorize us to do so.</p>
                        <p>7. Transfer of Information</p>
                        <p>Your information may be transferred to, and maintained on, computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from your jurisdiction.</p>
                        <p>If you are located outside India and choose to provide information to us, please note that we may transfer the data to India to process the Information.</p>
                        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                        <p>We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your data will take place to an organization or a country unless there are adequate controls in place including the security of your data.</p>
                        <p>8. Your Rights</p>
                        <p>You can always choose not to provide the requested information to us, it may however result in you not availing certain features of, or the entire, of our Services. You retain several rights in relation to your Personal Information as provided under applicable law. These may include the rights to:</p>
                        <p>access, confirm, and review Personal Information you may have provided;</p>
                        <p>correct Personal Information that may be inaccurate or irrelevant;</p>
                        <p>deletion and erasure of your Personal Information from the publicly available pages of the Platform;</p>
                        <p>receive Personal Information we hold about you in a portable format;</p>
                        <p>object to or restrict any form of processing you may not be comfortable with;</p>
                        <p>In order to exercise these rights, please contact us on the email address provided in Clause 3.3 above.&nbsp;</p>
                        <p>If you want to withdraw your consent or raise any objection to the use of your information for receiving any direct marketing information to which you previously opted-in, you can do so by contacting our customer support at above mentioned addresses. If you withdraw/object your consent, our use of your information before you withdrew/objected shall still be lawful.</p>
                        <p>9. Children&rsquo;s Privacy</p>
                        <p>Our Platform and Services are not meant for use by children and we knowingly do not collect Information of/from children. If it comes to our notice that we have collected Information from/of children, we shall take steps to remove that information from our servers. If you believe that we might have any Information that may have been collected from a child or has been provided by a child, please write to us at the email id provided in Clause 3.</p>
                        <p>10. Control the collection or use of the Information</p>
                        <p>If you have any reservations, constraints or apprehensions regarding the access to, collection, storage, or any other use of the Information which you have provided to us, you may withdraw your consent in the manner as set out in Clause 3 above.&nbsp;</p>
                        <p>11. Retention of Information</p>
                        <p>All Information provided by you, save and except upon withdrawal or termination, shall be retained in locations outside the direct control of Company (for instance, on servers or databases co-locates with hosting providers). We will delete Information based on a request received from you within a reasonable period and latest within 30 (thirty) days of receiving a deletion request. However, we may retain such portion of Information and for such periods as may be required under Applicable Law. Notwithstanding anything contained herein, Company may retain data after account deletion for reasons including but limited to the following purposes: If there is an unresolved issue relating to your account, or an unresolved claim or dispute; If we are required to by applicable law; and/or in aggregated and/or anonymized form; or Company may also retain certain information if necessary for its legitimate business interests, such as fraud prevention and enhancing Users' safety and security.&nbsp;</p>
                        <p>12. Cookies and other Tracking Technologies</p>
                        <p>Our Platform may utilize &ldquo;cookies&rdquo; and other Technical Information. &ldquo;Cookies&rdquo; are a small text file consisting of alphanumeric numbers used to collect the Information about Platform activity. The Technical Information helps us analyse web traffic and helps you by customizing the Platform to your preferences. Cookies in no way gives us access to your computer or mobile device. In relation to Cookies, you can deny access to the installation of the Cookies by modifying the settings on your web browser, however, this may prevent you from taking full advantage of the Platform.</p>
                        <p>Our use of Cookies and Technical Information allows us to improve Platform and your experience of Platform and Services. We may also analyse Technical Information that does not contain Personal Information for trends and statistics.</p>
                        <p>13. Third Party Services</p>
                        <p>We may use your Information to send you promotional Information about third parties which we think you may find interesting, if you tell us that you wish this to happen. We shall not be responsible for any disclosure of Information due to unauthorized third-party access or other acts of third parties or acts or omissions beyond our reasonable control and you agree that you will not hold us responsible for any breach of security unless such breach has been caused as a direct result of our negligence or wilful default.&nbsp;</p>
                        <p>We use support services of third-party platforms and/or companies to direct you to payment gateways when you opt to pay for our Services. Your financial information is collected, stored and retained by such third-party platforms. We and such third-party platforms undertake measures designed to provide a security level that is appropriate to the risks of processing your personal information. However, you are requested to check and consent to the &ldquo;Privacy Policy&rdquo; and &ldquo;Terms of Service&rdquo; of such third-party platforms in order to accept how such third-party platforms handle your information.</p>
                        <p>Once you leave the Platform, we are not liable for any use/ storage/ processing/ collection of your information obtained by any third-party websites or payment facilitators or provided by you to these third-parties or payment facilitators. Such entities and their respective websites/platforms may be governed by their own &ldquo;Privacy Policy&rdquo; and &ldquo;Terms of Service&rdquo;, which are beyond our control.</p>
                        <p>14. Data Security</p>
                        <p>You agree and accept that your Information may be stored in third-party cloud service infrastructure providers. While all reasonable attempts have been taken from our end to ensure the safe and secure storage of your data, we shall not be liable for any data breach on the part of the third-party cloud service infrastructure provider that was beyond our control. In addition to the security measures put in place by the third-party cloud service infrastructure provider for safe and secure storage of your Information, we use certain physical, managerial, technical or operational safeguards as per industry standards and established best practices to protect the Information we collect. We use reasonable security practices and procedures and use secure servers as mandated under applicable laws for the protection of your Information. We review our Information collection, storage, and processing practices, including physical security measures to guard against unauthorized access to systems. However, as effective as these measures are, no security system is impenetrable. We cannot guarantee the security of our database, nor can we guarantee that the Information you supply will not be intercepted while being transmitted to us over the internet. You accept the inherent security implications of data transmission over the internet and the internet cannot always be guaranteed as completely secure. Therefore, your use of the Platform will be at your own risk. If you have any concerns, please feel free to contact us at the details given in Clause 3 above.</p>
                        <p>15. Changes and updates to Policy</p>
                        <p>We may modify or revise the Privacy Policy from time to time and shall accordingly notify you of any changes to the Privacy Policy by posting the revised Privacy Policy on the Platform with an updated date of revision. We shall endeavour to review, revise, update, modify, amend or correct the Privacy Policy on a regular and routine basis, especially whenever a significant update is made to the technology employed by us. You must periodically review the Privacy Policy for the latest information on our privacy practices. In the event you continue to use the Platform and our services after any update in the Privacy Policy, your use of the Platform shall be subject to such updated privacy policy. Your continued usage of Services, post any amendment would deem to mean that you accept and understand the revised Privacy Policy. Further, we retain the right at any time to deny or suspend access to all, or any part of, the service to anyone who we reasonably believe has violated any provision of this Privacy Policy.</p>
                        <p>17. Miscellaneous</p>
                        <p>THE INVALIDITY OR UNENFORCEABILITY OF ANY PART OF THIS PRIVACY POLICY SHALL NOT PREJUDICE OR AFFECT THE VALIDITY OR ENFORCEABILITY OF THE REMAINDER OF THIS PRIVACY POLICY. THIS PRIVACY POLICY DOES NOT APPLY TO ANY INFORMATION OTHER THAN THE INFORMATION COLLECTED BY US THROUGH THE PLATFORM. THIS PRIVACY POLICY SHALL BE INAPPLICABLE TO ANY UNSOLICITED INFORMATION YOU PROVIDE US THROUGH THE PLATFORM OR THROUGH ANY OTHER MEANS. ALL UNSOLICITED INFORMATION SHALL BE DEEMED TO BE NON-CONFIDENTIAL AND WE SHALL BE FREE TO USE AND/ OR DISCLOSE SUCH UNSOLICITED INFORMATION WITHOUT ANY LIMITATIONS. THE RIGHTS AND REMEDIES AVAILABLE UNDER THIS POLICY MAY BE EXERCISED AS OFTEN AS NECESSARY AND ARE CUMULATIVE AND NOT EXCLUSIVE OF RIGHTS OR REMEDIES PROVIDED BY LAW. RIGHTS UNDER THIS POLICY MAY BE WAIVED ONLY IN WRITING. DELAY IN EXERCISING OR NON-EXERCISE OF ANY SUCH RIGHT OR REMEDY DOES NOT CONSTITUTE A WAIVER OF THAT RIGHT OR REMEDY, OR ANY OTHER RIGHT OR REMEDY.</p>
                        <p>18. Governing Laws and Jurisdiction</p>
                        <p>This Privacy Policy, our Services and the use of it is governed by the laws of India and the courts in Bangalore, India shall have exclusive jurisdiction over any disputes connected to our Platform or the Services.&nbsp;</p>
                        <p>YOUR ACCEPTANCE OF THE PRIVACY POLICY</p>
                        <p>BY USING OR VISITING THIS PLATFORM, YOU SIGNIFY YOUR AGREEMENT OF THIS PRIVACY POLICY. IF YOU DO NOT AGREE TO ANY OF THESE TERMS, PLEASE DO NOT USE THIS PLATFORM OR SERVICES.</p>
                        </div>
                </Col>
            </Row>
        </div>
    )
}