export const projects = [
  {
    slno: '1',
    name: 'Ecommerce',
    date: '12 july 2021',
    text: 'Project Description in dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '2',
    name: 'Saas',
    date: '12 july 2021',
    text: 'Lorem ipsum is a dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '3',
    name: 'Enterprise Tech',
    date: '12 july 2021',
    text: 'Project Description in dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '4',
    name: 'Blockchain/Crypto',
    date: '12 july 2021',
    text: 'Lorem ipsum is a dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '5',
    name: 'Fintech',
    date: '12 july 2021',
    text: 'Project Description in dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '6',
    name: 'Edtech',
    date: '12 july 2021',
    text: 'Project Description in dummy text',
    view: <i class="far fa-eye"></i>,
  },
  {
    slno: '7',
    name: 'Martech',
    date: '12 july 2021',
    text: 'Project Description in dummy text',
    view: <i class="far fa-eye"></i>,
  },
];
