import React, { Component } from 'react'
import {Row, Col} from 'react-bootstrap';
export const Terms = () => {
    return (
        <div>
            <Row>
                <Col sm={12}>
                <div data-testid="richTextElement">
                    <h2>Terms &amp; Conditions</h2>
                    <p>Shopfree Technologies Private Limited (&ldquo;Company&rdquo;), a company incorporated under Companies Act, 2013 having its registered office at No. 6, 1st Cross, Virupakshapura, Bangalore - 560097, provides automated text content through its website (referred to as &ldquo;Services&rdquo;) available at&nbsp;<a href="http://www.ellipsis-ai.com/" target="_blank" rel="noopener">www.ellipsis-ai.com</a>&nbsp;(referred to as &ldquo;Platform&rdquo;).</p>
                    <p>The Company requests the User (as defined below) to carefully go through these terms &amp; conditions (&ldquo;Terms of Service&rdquo; or&ldquo;Agreement&rdquo; or &ldquo;TOS&rdquo; or &ldquo;Terms&rdquo;), prior to accessing the Platform or availing Services (as defined below) via the Platform. If User continues to browse and use the Platform to avail Services, User irrevocably and unconditionally is agreeing to comply with, abide by and be bound by all these obligations as stipulated in this TOS, which together read with our privacy policy (&ldquo;Privacy Policy&rdquo;); and any other applicable policies referred to herein or made available on the Platform (collectively referred as &ldquo;Terms and Conditions&rdquo;). The Terms and Conditions shall govern the Company&rsquo;s relationship with User in relation to the usage of the Platform. These Terms and Conditions supersede all previous oral, written terms and conditions (if any) communicated to User and shall act as a binding agreement between Company and the User.</p>
                    <p>IF YOU DO NOT AGREE TO BE BOUND BY ALL TERMS AND CONDITIONS CAPTURED IN THE TOS, PLEASE DO NOT USE THE PLATFORM AND/OR ITS SERVICES.</p>
                    <p>1. Definitions</p>
                    <p>"Company&rdquo;," "we", &ldquo;Ellipsis&rdquo;, "us", or "our" means Shopfree Technologies Private Limited and any other companies that are its subsidiaries and affiliates.</p>
                    <p>"Service(s)" means services provided through the Platform, as described in further detail under clause 3 below. The Services provided through the Platform may change from time to time, at the sole discretion of the Company.</p>
                    <p>&ldquo;User&rdquo; or &ldquo;You&rdquo; shall mean any person or entity who is a visitor on the Platform and/or shall avail Services on the Platform, or his/her representatives or affiliates who are registered on the Platform.</p>
                    <p>&ldquo;Customer&rdquo; shall mean those Users who have sought to avail Services via the Platform.</p>
                    <p>2. Updation of Terms and Conditions</p>
                    <p>Your use of the Platform is subject to the Terms and Conditions, which may be updated, amended, modified or revised by us from time to time with/without notice to you. To ensure that you are aware of any additions, revisions, amendments or modifications that we may have made to these Terms and Conditions, it is important for you to refer to the Terms and Conditions from time to time. The updated Terms and Conditions shall be effective immediately and shall supersede these. We shall not be under an obligation to notify you of any changes to the Terms and Conditions. You shall be solely responsible for reviewing the Terms and Conditions from time to time for any modifications. If you continue to use the Website, Content and/or Services after the Updated Terms and Conditions have been published, it shall be deemed that you have read and understood and accept the Updated Terms and Conditions. Any reference to Terms of Service, TOS, Agreement made herein shall refer to the latest version of the Terms of Service.</p>
                    <p>3. Service(s) provided to Users</p>
                    <p>We provide you a Platform that collates your content requirements and automatically provides original and unique content as per the specifications provided.&nbsp;</p>
                    <p>4. Eligibility</p>
                    <p>By using Platform, you affirm that you are at least eighteen (18) years of age and are fully able, and competent to enter into the terms, conditions, obligations, affirmations, representations, warranties set forth in the Terms and Conditions, and to abide by and comply with the terms stated therein. Registration of User in the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents, or person with unsound mind etc. are not eligible to use the Platform. By accessing the Website or by accessing any of the Services or Content on any other Authorized Device, it is deemed that the User has read and understood and accepted these Terms.</p>
                    <p>If you will be using the Services on behalf of an organization, you agree to these Terms on behalf of that organization and you represent that you have the authority to do so.</p>
                    <p>5. Enterprise Account Registration (applicable to body corporate customer).</p>
                    <p>In order to avail the Services, you must first complete the registration process and create an account in the name of the respective Company (&ldquo;Enterprise Account&rdquo;). The terms and conditions associated with the Enterprise Account will be governed by a separate services agreement executed between company and us. Pursuant to this, the designated SuperAdmin of the Enterprise Account shall create individual accounts for authorized members of the company (&ldquo;Team Account&rdquo;) with individual login credentials.</p>
                    <p>If you are using a Team Account:</p>
                    <p>You are entirely responsible for safeguarding and maintaining the confidentiality of your login credentials. Should you login to the Platform using such login credentials, it shall be deemed that your Team Account has been accessed by you or any third-party to whom you have granted access to the Team Account. You agree to notify us or the Company immediately if you suspect or become aware of any unauthorized use of your Team Account or any unauthorized access to the password for any Team Account.</p>
                    <p>6. User Account Registration</p>
                    <p>Users who are at least eighteen (18) years of age may create an account if they wish to avail our Services. Any use of our Services by anyone under eighteen (18) years of age is expressly prohibited and by using our Services you represent and warrant that you are eighteen (18) years or older. In order to use the Platform, you have to create an account (&ldquo;Account&rdquo;), you shall provide true and accurate information while creating your Account. The Information collected while creating your Account will be governed by our Privacy Policy. You are responsible for maintaining the confidentiality of your login credentials and are fully responsible for all activities that occur under your Account. Post entering your details (email ID/phone number) in the Platform, one-time verification shall be conducted by the Company. Post such verification the Account shall be created.</p>
                    <p>You are entirely responsible for safeguarding and maintaining the confidentiality of your login credentials. Only one Account can be created by one Creator, should the Company become aware of multiple Accounts attributed to the same Creator, the Company reserves the right at its sole discretion to terminate or suspend such Accounts. You agree to notify us immediately if you suspect or become aware of any unauthorized use of your Account or any unauthorized access to the password for any Account. You further agree not to use the Account or log in with the username and password of another User of the Site if (a) you are not authorized to use both or (b) the use would violate the Terms of Service.</p>
                    <p>7. Platform License</p>
                    <p>Subject to your compliance with the TOS, Company grants you a limited, non-exclusive, non-transferable license: (i) to view, download and print any content of Platform solely for your personal and non-commercial purposes; and (ii) to access, modify, edit and download any content, to which you are permitted access solely for your use. You have no right to sublicense the license rights granted herein.</p>
                    <p>You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast or otherwise exploit the Platform and Services, except as expressly permitted in the TOS. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Company or its licensors, except for the licenses and rights expressly granted in the TOS. The Platform and the intellectual property rights vested therein is owned by the Company.</p>
                    <p>8. Fees</p>
                    <p>You agree to Pay to the Compaby any fees for the Services availed by you, in accordance with the pricing and payment plans presented to you by the Company on the platform and the website. Payment against fees can be made online through credit Card/internet banking etc. or any mode of payment which is made available to the User in the Platform. The Fees paid by you is non-refundable, except as provided in these Terms and Conditions.</p>
                    <p>9. Use of Your Information and Content and other content displayed on the Platform</p>
                    <p>If you create, transmit, submit, display or otherwise make available any information while using the Services, you may provide only information that you own or have the right to use. We may only use the information you provide as permitted by our Privacy Policy and applicable law. Please closely review our Privacy Policy for more information regarding how we use and disclose your personal information. Our Privacy Policy is hereby incorporated into these Terms of Service by this reference.</p>
                    <p>We reserve the right to maintain, delete or destroy all information and materials posted or uploaded through the Services, pursuant to our internal record retention and/or destruction policies. We (may/may not) make use of third-party cloud services providers or use our own service infrastructure for hosting the servers and databases. While we make commercially reasonable efforts to ensure that the data stored on our servers is persistent and always available to the User, we will not be responsible in the event of failure of the third-party servers or any other factors outside our reasonable control that may cause the User&rsquo;s data to be permanently deleted, irretrievable, or temporarily inaccessible.</p>
                    <p>You acknowledge and agree that we may preserve your information and may also disclose your related information if required to do so by law; or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply with legal process, applicable laws or government requests; (b) enforce these TOS; (c) respond to claims that any of your usage of the Platform violates the rights of third parties; (d) detect, prevent, or otherwise address fraud, security or technical issues; or (e) protect the rights, property, or personal safety of the Platform, its users, or the public.</p>
                    <p>10. Third Party Services</p>
                    <p>While availing Services, Users may connect with third-party service providers. The Company is not responsible for, and does not endorse, any third-party services mentioned on the Platform. It is hereby stated that Company shall in no way be responsible for any acts or omissions of third parties. Any transaction, dealings or communication otherwise that the User may have with such third parties are at the User&rsquo;s own risk and we make no warranties, express or implied regarding the quality or suitability of the services or products of such third-party vendors. You may be redirected to a third-party website upon clicking on such links, these websites will be governed by its privacy policy and terms of use. We shall not be responsible for any transaction or dissemination of information that may take place while accessing these third-party websites.</p>
                    <p>11. Rules and Conduct</p>
                    <p>As a condition of use, you promise not to use the Services for any purpose that is prohibited by the TOS; or other rules or policies implemented by us from time to time; or in violation of any applicable laws. The Services (including, without limitation) is provided only for your own personal and non-commercial use.</p>
                    <p>By way of example, and not as a limitation, you shall not (and shall not permit any third party to) take any action that: (i) would constitute a violation of any applicable law, rule or regulation; (ii) infringes on any intellectual property or other right of any other person or entity; (iii) is threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another&rsquo;s privacy, tortuous, obscene, offensive, or profane; or (iv) impersonates any person or entity. The Company reserves the right to disable any Account from the Platform at any time for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities; or if Company is concerned that You may have violated the Terms of Service), or for no reason at all with or without notice to the User/Users.</p>
                    <p>Additionally, you shall not share any information that: (i) may be harmful to minors or children below the age of 18 (eighteen) years; (ii) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation; and (iii) is invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; (iv) harms minors in any manner; (v) infringes any patent, trademark, copyright or other proprietary rights; (vi) violates any laws for time being; and (vii) impersonate any person.</p>
                    <p>Furthermore, you shall not (directly or indirectly): (i) take any action that imposes or may impose an unreasonable or disproportionately large load on Company&rsquo;s (or its third party providers&rsquo;) infrastructure; (ii) interfere or attempt to interfere with the proper working of the Platform or any activities conducted on the Platform; (iii) bypass any measures we may use to prevent or restrict access to the Platform (or parts thereof); (iv) decipher, decompile, disassemble, reverse engineer or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Platform, except to the limited extent applicable laws specifically prohibit such restriction; (v) modify, translate, or otherwise create derivative works of any part of the Platform; or (vi) copy, rent, lease, distribute, or otherwise transfer any or all of the rights that you receive hereunder.</p>
                    <p>You will not access the Platform, and/or its Services, or the personal information of other Users, available on the Website in order to build a similar or competitive website, product, or service.</p>
                    <p>You agree to immediately notify us of any unauthorised use, or suspected unauthorized use of Your Profile, or any other breach of security, in relation to Your personal information on the Website.</p>
                    <p>12. Contact</p>
                    <p>You agree that we may contact you through telephone, email, SMS, WhatsApp or any other means of communication for the purpose of:</p>
                    <p>Obtaining feedback in relation to Platform or our Services;</p>
                    <p>Resolving any complaints, information, or queries; and</p>
                    <p>You agree to provide your fullest cooperation further to such communication by Company.</p>
                    <p>By submitting suggestions or other feedback regarding our Services/Platform, you agree that we can use and share such feedback for any purpose without any compensation to you and we are under no obligation to give such feedback confidential.</p>
                    <p>13. Profile Ownership and Editing Rights</p>
                    <p>We ensure easy access to the Users by providing a tool to update your profile information. We reserve the right to moderate the changes or updates requested by you and we shall take an independent decision whether to publish or reject the requests submitted for the respective changes or updates in your profile. You hereby represent and warrant that you are fully entitled, under applicable law, to provide information as part of your profile or otherwise while using our Services, and that no such information breaches any third-party rights, including intellectual property rights and applicable data protection laws. Upon becoming aware of a breach of the foregoing representation, we may modify or delete parts of your profile information at our sole discretion with or without notice to you.</p>
                    <p>Excluding Your Account information, you acknowledge that the Website, the entire content, Services, and all the intellectual property rights, including copyrights, patents, trademarks, designs, and trade secrets in relation to the above are solely owned by us.</p>
                    <p>Applicable to Enterprise Accounts:</p>
                    <p>The terms mentioned apply to Users who access our Platform via Enterprise Account or Team Accounts. In addition to the above, the Company is entitled to moderate the changes or updates requested by you and we shall take an independent decision whether to publish or reject the requests submitted for the respective changes or updates in your profile.</p>
                    <p>14. Rights and Obligation relating to the usage of the Platform</p>
                    <p>Users shall be prohibited from carrying out any illegal acts in the Platform including but not limited to acts mentioned below:</p>
                    <p>violating or attempting to violate the integrity or security of the Platform;</p>
                    <p>transmitting any information on or through the Platform that is disruptive or competitive to the provision of our Services;</p>
                    <p>intentionally submitting on the Platform any incomplete, false or inaccurate information;</p>
                    <p>making any unsolicited communications to other Users;</p>
                    <p>using any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Platform;</p>
                    <p>running a coded script/algorithm on the Platform to extract any information or perform any activity. All action on the Platform should be done by human interaction, and machine interaction is strictly prohibited;</p>
                    <p>circumventing or disabling any digital rights management, usage rules, or other security features of the Platform;</p>
                    <p>Any unlawful activities in the Platform which are prohibited by laws of India.</p>
                    <p>The Company shall, upon obtaining knowledge by itself or been brought to actual knowledge by an affected person in writing or through email signed with electronic signature about any such information as mentioned above, be entitled to disable such information that is in contravention of this Clause. We shall also be entitled to preserve such information and associated records for at least 90 (ninety) days for production to governmental authorities for investigation purposes. In case of non-compliance with any applicable laws, rules or regulations, or the Agreement (including the Privacy Policy) by a User, we shall have the right to immediately terminate your access or usage rights to the Platform and Services and to remove non-compliant information from the Platform.</p>
                    <p>We may disclose or transfer User-generated information to our affiliates or governmental authorities in such manner as permitted or required by applicable law, and you hereby consent to such transfer. In accordance with the applicable laws, we shall transfer sensitive personal data or information including any information, to any other body corporate or a person in India, or located in any other country, that ensures the same level of data protection that is adhered to by us, only if such transfer is necessary for the performance of the lawful contract between Company or any person on its behalf and the User or where the User has consented to data transfer.</p>
                    <p>15. Modification</p>
                    <p>We reserve the right, at any time and in with sole discretion, to change, modify, or amend the Website (in whole, or in part) or any of its Services or Content (in whole, or in part), in compliance with the applicable legal and regulatory framework. You agree that We will not be liable to You for any change, modification or amendment of the Website or its Services, or any part thereof.</p>
                    <p>16. Support</p>
                    <p>The Company offers an email-based support system. In case you require any assistance or support, you may access support resources or contact our support by emailing at&nbsp;<a href="mailto:support@ellipsis-ai.com" target="_self">support@ellipsis-ai.com</a>. The Company shall strive to revert to every complaint within 48 hours of receipt of the complaint. Further, the Company shall take best possible efforts to redress the complaint within thirty (30) days of receipt of the complaint.</p>
                    <p>The User agrees and acknowledges that the Company shall address and attempt to resolve the complaint received in accordance with the standard policies and procedures adopted by the Company, the User&rsquo;s disapproval/discontent with the outcome/mode of redressal shall not be deemed to mean non-redressal of the complaint by the Company. Any suggestions by Company regarding use of the Services shall not be construed as a warranty.</p>
                    <p>17. Termination</p>
                    <p>Termination/ Suspension of Services:</p>
                    <p>We have the right to temporarily suspend access to the whole or any part of the Services for any reason whatsoever (including but not limited to technical/operational reasons) and shall be under no liability to you in such an event. Further, we may, but shall not be obliged to, give you notice of any interruption of access to the Service.</p>
                    <p>We may temporarily suspend access to the whole or any part of the Services for pre-scheduled maintenance. If you choose to access the Platform or avail Services during such pre-scheduled maintenance, we cannot guarantee the availability of the Services and/or functionality of the Platform.</p>
                    <p>Termination/ Suspension of Accounts:</p>
                    <p>We may terminate your usage of the Platform at any time for any reason, including breach of the Terms and Conditions. We have the right (but not the obligation) to refuse to grant access to Platform. Except for the rights and license granted in these terms, we reserve all other rights and grant no other rights or licenses, implied or otherwise.</p>
                    <p>Once temporarily suspended, indefinitely suspended or terminated, the User may not continue to use the Platform under the same account, a different account or re-register under a new account. On termination of an account due to the reasons mentioned herein, such User shall no longer have access to data, messages and other material kept on the Platform by such User. All provisions of the TOS, which by their nature should survive termination, shall survive termination, including, without limitation, warranty disclaimers, indemnity and limitations of liability.</p>
                    <p>18. Disclaimer</p>
                    <p>THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY CONTENT) IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; AND IS WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE OR USAGE OF TRADE, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. THE COMPANY and SERVICE PROVIDER (INCLUDING) ITS DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, SPONSORS AND PARTNERS DO NOT WARRANT THAT: (A) THE SERVICE WILL BE SECURE OR AVAILABLE AT ANY PARTICULAR TIME OR LOCATION; (B) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (C) ANY CONTENT OR SOFTWARE AVAILABLE AT OR THROUGH THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; OR (D) THE RESULTS OF USING THE SERVICE WILL MEET YOUR REQUIREMENTS. YOUR USE OF THE SERVICE IS SOLELY AT YOUR OWN RISK. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
                    <p>19. Indemnification</p>
                    <p>You shall defend, indemnify, and hold harmless the Company, its affiliates/subsidiaries/joint venture partners and each of its, and its affiliates&rsquo;/subsidiaries/joint venture partners&rsquo; employees, contractors, directors, suppliers and representatives from all liabilities, losses, claims, and expenses, including reasonable attorneys&rsquo; fees, that arise from or relate to (i) your use or misuse of, or access to, the Services and Platform; or (ii) your violation of the Terms and Conditions; or any applicable law, contract, policy, regulation or other obligation. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in connection therewith.</p>
                    <p>20. Limitation of Liability</p>
                    <p>TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL COMPANY (INCLUDING ITS DIRECTORS, EMPLOYEES, AGENTS, SPONSORS, PARTNERS, SUPPLIERS, CONTENT PROVIDERS, LICENSORS OR RESELLERS,) BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SERVICES (I) FOR ANY LOST PROFITS, DATA LOSS, LOSS OF GOODWILL OR OPPORTUNITY, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, (II) FOR YOUR RELIANCE ON THE SERVICES (III) FOR ANY MATTER BEYOND ITS OR THEIR REASONABLE CONTROL, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF ANY OF THE AFOREMENTIONED DAMAGES.</p>
                    <p>21. Exemptions to liability of Company</p>
                    <p>You further agree and confirm that Company shall not be responsible, in any manner whatsoever, for any delay/unavailability of Services or failure to meet its obligations under the Terms and Conditions, which may be caused, directly or indirectly, due to:</p>
                    <p>your failure to cooperate;</p>
                    <p>your unavailability and/or unresponsiveness;</p>
                    <p>your failure to provide accurate and complete information;</p>
                    <p>your failure to provide or facilitate the submission of User Materials in timely manner;</p>
                    <p>any event beyond Company&rsquo;s reasonable control.</p>
                    <p>22. Governing Law</p>
                    <p>This Agreement shall be governed by and construed in accordance with the laws of India without regard to the conflict of law provisions thereof. All claims, differences and disputes arising under or in connection with or in relation hereto the Platform or Services, the Terms or any transactions entered into on or through the Platform or Services shall be subject to the exclusive jurisdiction of the courts at Bangalore, India and you hereby accede to and accept the jurisdiction of such courts.</p>
                    <p>23. Miscellaneous</p>
                    <p>The Terms and Conditions are the entire agreement and understanding between you and Company with respect to the Services and usage of Platform.</p>
                    <p>If any provision of the Terms and Conditions are found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms and Conditions will otherwise remain in full force and effect and enforceable.</p>
                    <p>The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p>
                    <p>The Terms and Conditions are personal to you, and are not assignable or transferable by you except with Company&rsquo;s prior written consent. Company may assign, transfer or delegate any of its rights and obligations hereunder without any consent.</p>
                    <p>No agency, partnership, joint venture, or employment relationship is created as a result of the Terms and Conditions and neither party has any authority of any kind to bind the other in any respect.</p>
                    <p>All notices under the Terms and Conditions will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; or two days after it is sent, if sent for next day delivery by recognized overnight delivery service.</p>
                    <p><br /></p>
                    <p>24. Contact</p>
                    <p>If you have any questions regarding the Services or usage of the Platform, please contact Company at&nbsp;<a href="mailto:support@ellipsis-ai.com" target="_self">support@ellipsis-ai.com</a>. Please note that for the purpose of validation, you shall be required to provide information (including, but not limited to contact number or registered mobile number, etc.) for the purpose of validation and taking your service request.</p>
                    </div>
                </Col>
            </Row>
        </div>
    )
}